### ISSUE TITLE
[EPIC #6]: Social Features and User Interactions

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#10]
* **Description**: Facilitating social interactions between users, including adding friends, reporting posts, and joining book clubs.

* **User stories:**
  - [ ] [USER STORY: Add people as friends](x)
  - [ ] [USER STORY: Report post/comment/user](x)
  - [ ] [USER STORY: Join a bookclub](x)
  - [ ] [USER STORY: Browse other users’ profiles](x)
