### ISSUE TITLE
[USER STORY]: Profile customisation

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#12]
_Related to [Epic #1: User Account and Profile Management](https://github.com/chl03rivs/bookwyrms-alliance/issues/4)_

* *As a* registered user, 
* *I want* to customize my profile,
* *So that* it reflects my personality

## ACCEPTANCE CRITERIA:

- [ ] Users can upload profile pictures.
- [ ] Users can edit personal information (e.g., bio).
- [ ] Users can update their profile background or theme.

## TASKS:

- [ ] Create forms for editing user profiles.
- [ ] Add options for uploading profile pictures and changing the theme.
- [ ] Update the profile view to reflect changes
