### ISSUE TITLE
[USER STORY]: Change profile information

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#13]
Related to [Epic #1: User Account and Profile Management](https://github.com/chl03rivs/bookwyrms-alliance/issues/4)

* *As a* registered user, 
* *I want* to be able to change the information on my profile,
* *So that* it matches my personality and taste.

## ACCEPTANCE CRITERIA:

- [ ] Users can edit their bio, username, and preferences.
- [ ] Changes are reflected immediately on the profile.
- [ ] Profile updates are validated for input correctness.

## TASKS:

- [ ] Create an edit profile form.
- [ ] Implement validation logic.
- [ ] Update the database with profile changes.
