### ISSUE TITLE
[USER STORY]: User created lists

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#16]
Related to [Epic #1: User Account and Profile Management](https://github.com/chl03rivs/bookwyrms-alliance/issues/4)

* *As a* registered user, 
* *I want* to be able to create lists of books,
* *So that* I can organise my favourites, to-be-read or favourite genres.

## ACCEPTANCE CRITERIA:

- [ ] Users can create multiple book lists (e.g., "Read", "To be read").
- [ ] Users can add and remove books from lists.
- [ ] Lists are displayed on the user's profile.

## TASKS:

- [ ] Create models for book lists.
- [ ] Implement forms for managing book lists.
- [ ] Update profile views to display book lists.
