### ISSUE TITLE
[USER STORY]: User log out

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#17]
Related to [Epic #1: User Account and Profile Management](https://github.com/chl03rivs/bookwyrms-alliance/issues/4)

* *As a* registered and signed-in user, 
* *I want* to be able to log out,
* *So that* I can end my session when I want to, before leaving the app.

## ACCEPTANCE CRITERIA:

- [ ] Users can log out from any page.
- [ ] Sessions are terminated securely upon logout.
- [ ] Users are redirected to the homepage after logging out.

## TASKS:

- [ ] Add a logout function to the navigation bar.
- [ ] Implement session termination on logout.
- [ ] Redirect users to the homepage after logout.
