### ISSUE TITLE
[USER STORY]: Search feature

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#18]
Related to [Epic #2: Content Discovery and Navigation](https://github.com/chl03rivs/bookwyrms-alliance/issues/6)

* *As a*general user, 
* *I want* to be able to search for books and authors,
* *So that* I can easily find discussions, recommendations, or ideas of what to read.

## ACCEPTANCE CRITERIA:

- [ ] Users can search for books, authors, and genres.
- [ ] Search results are relevant to the input query.
- [ ] Users can click search results to view details or discussions

## TASKS:

- [ ] Create a search form.
- [ ] Set up search logic in the backend.
- [ ] Display search results in a user-friendly format.
