### ISSUE TITLE
[USER STORY]: View posts and comments

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#19]
Related to [Epic #2: Content Discovery and Navigation](https://github.com/chl03rivs/bookwyrms-alliance/issues/6)

* *As a* general user, 
* *I want* to be able to view the posts on the platform and their comments,
* *So that* I can read their content

## ACCEPTANCE CRITERIA:

- [ ] Users can view all posts and their comments.
- [ ] Posts and comments are displayed in chronological order.
- [ ] Users can navigate through pages of posts.

## TASKS:

- [ ] Create views to display posts and comments.
- [ ] Style the views to show content cleanly.
- [ ] Implement pagination for posts.
