### ISSUE TITLE
[USER STORY]: Filter feature

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#20]
Related to [Epic #2: Content Discovery and Navigation](https://github.com/chl03rivs/bookwyrms-alliance/issues/6)

* *As a* general user,
* *I want* to be able to filter the community posts by author/genre/topic/tag,
* *So that* I can have a tailored experience.

## ACCEPTANCE CRITERIA:

- [ ] Users can filter posts based on authors, genres, topics. or tags
- [ ] Filtering results show only relevant posts.
- [ ] Filters are easily accessible on all relevant pages.

## TASKS:

- [ ] Implement logic for filtering on the backend.
- [ ] Add the filtering options for posts in the frontend
- [ ] Style the filtered posts view.
