### ISSUE TITLE
[USER STORY]: Creating posts

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#21]
Related to [Epic #3: Post and Comment Creation](https://github.com/chl03rivs/bookwyrms-alliance/issues/8)

* *As a* registered user, 
* *I want* to be able to write a post about a book/author,
* *So that* I can share my opinion with others

## ACCEPTANCE CRITERIA:

- [ ] Users can write and publish posts about books and authors.
- [ ] Posts are displayed publicly for all users to see.
- [ ] Users can tag posts with relevant authors or books.

## TASKS:

- [ ] Create forms for writing posts.
- [ ] Set up backend logic for saving posts.
- [ ] Display posts with tags for books/authors on the frontend.
