### ISSUE TITLE
[USER STORY]: Write a post about non-book topics

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#22]
Related to [Epic #0: ]()

* *As a* registered user, 
* *I want* to be able to talk about other topics than books,
* *So that* I can make real connections to other users and make friends.

## ACCEPTANCE CRITERIA:

- [ ] Users can create discussion topics unrelated to books.
- [ ] Non-book topics are categorized separately.
- [ ] Users can filter between book-related and other content.

## TASKS:

- [ ] Ensure that book/author selection isn't mandatory in the post creation form
- [ ] Display non-book topics in a separate section.
