### ISSUE TITLE
[USER STORY]: Comments

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#23]
Related to [Epic #3: Post and Comment Creation](https://github.com/chl03rivs/bookwyrms-alliance/issues/8)

* *As a* registered user, 
* *I want* to be able to leave comments under posts,
* *So that* I can share my opinion and be a part of the conversation.

## ACCEPTANCE CRITERIA:

* [ ] Users can write and publish comments under posts in the community
* [ ] Comments are displayed publicly for all users to see
* [ ] Users can write comments in response to another comment

## TASKS:

* [ ] Create forms for writing comments
* [ ] Set up backend logic for sending comments
* [ ] Display comments on the frontend
