### ISSUE TITLE
[USER STORY]: Comments and posts updates

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#24]
Related to [Epic #3: Post and Comment Creation](https://github.com/chl03rivs/bookwyrms-alliance/issues/8)

* *As a* registered user, 
* *I want* to be able to go back and update my own posts and comments,
* *So that* I can fix any mistake or add new details to it.

## ACCEPTANCE CRITERIA:

- [ ] Users can edit their own posts and comments.
- [ ] Changes to posts and comments are reflected immediately.
- [ ] Users receive a confirmation when their post or comment has been edited.

## TASKS:

- [ ] Create an "edit" option for user posts and comments.
- [ ] Implement backend logic for updating posts and comments.
- [ ] Test the edit functionality to ensure changes are saved correctly.
