### ISSUE TITLE
[USER STORY]: Failed publication user alert

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#25]
Related to [Epic #4: Error Handling and User Feedback](https://github.com/chl03rivs/bookwyrms-alliance/issues/7)

* *As a* registered user,
* *I want* to be notified that my post/comment wasn't successfully published & the reason why,
* *So that* I can fix the problem and resubmit it.

## ACCEPTANCE CRITERIA:

- [ ] Users receive a clear error message if a post/comment is/can not published.
- [ ] The error message includes details on how to fix the issue.
- [ ] Users can retry publishing the post/comment after fixing errors.

## TASKS:

- [ ] Create error handling for post/comment submissions.
- [ ] Display error messages on failed submissions.
- [ ] Implement retry functionality.
