### ISSUE TITLE
[USER STORY]: User Favourites on Profile

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#3]
Related to [Epic #1: User Account and Profile Management](https://github.com/chl03rivs/bookwyrms-alliance/issues/2)

* *As a* user, 
* *I want* to be able to favourite books,
* *So that* I can display my taste on my profile

## ACCEPTANCE CRITERIA:

- [ ] Users can mark books as favorites.
- [ ] Favorite books are displayed on the user profile.
- [ ] Users can remove books from favorites.

## TASKS:

- [ ] Create a model for favorite books.
- [ ] Create a form for adding/removing favorite books.
- [ ] Update the user profile page to display favorite books.
