### ISSUE TITLE
[USER STORY]: Admin accounts

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#30]
Related to [Epic #5: Admin Tools and Moderation](https://github.com/chl03rivs/bookwyrms-alliance/issues/9)

* *As an* admin, 
* *I want* to have an account with special authorizations,
* *So that* I can moderate the activity of users and the content on the platform

## ACCEPTANCE CRITERIA:

- [ ] Admin accounts have special access rights compared to normal users.
- [ ] Admins can perform actions like banning users, removing content, etc.
- [ ] Admin access is restricted to authorized users only.

## TASKS:

- [ ] Set up a role-based access control system.
- [ ] Assign admin privileges to specific users.
- [ ] Ensure security for admin actions.
