### ISSUE TITLE
[USER STORY]: Removing flagged content

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#32]
Related to [Epic #5: Admin Tools and Moderation](https://github.com/chl03rivs/bookwyrms-alliance/issues/9)

* *As an* admin, 
* *I want* to be able to remove a user's post or comment,
* *So that* I can keep the platform free of inappropriate content.

## ACCEPTANCE CRITERIA:

- [ ] Admins can remove posts or comments from users.
- [ ] Removed posts/comments are no longer visible on the platform.
- [ ] Admin actions are logged for moderation purposes.

## TASKS:

- [ ] Add views for admins to view flagged content.
- [ ] Implement routes for removing or hiding inappropriate posts/comments.
- [ ] Write unit tests to cover the moderation process.
