### ISSUE TITLE
[USER STORY]: Overview of users' moderation requests

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#34]
Related to [Epic #5: Admin Tools and Moderation](https://github.com/chl03rivs/bookwyrms-alliance/issues/9) and [Epic #6: Social Features and User Interactions](https://github.com/chl03rivs/bookwyrms-alliance/issues/10) ([User story: ]())

* *As an* admin, 
* *I want* to have an easy overview of pending requests from users,
* *So that* I can save time when approving/denying them.

## ACCEPTANCE CRITERIA:

- [ ] Admins can view all pending user requests (e.g., flagged user, post or comment).
- [ ] Admins can approve/deny requests directly from a single dashboard.
- [ ] The status of pending requests is updated in real-time.

## TASKS:

- [ ] Implement a dashboard view for pending requests.
- [ ] Create functionality for approving/denying requests.
- [ ] Ensure requests are updated instantly after admin action.
