### ISSUE TITLE
[USER STORY]: Add users as friends

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#36]
Related to [Epic #6: Social Features and User Interactions](https://github.com/chl03rivs/bookwyrms-alliance/issues/10)

- *As a* user,
- *I want* to be able to add people as friends,
- *So that* I can quickly find them and message them.

## ACCEPTANCE CRITERIA:

- [ ] Users can send and accept friend requests.
- [ ] Friend list is visible on the user's profile.
- [ ] Users can message friends directly.

## TASKS:

- [ ] Implement friend request functionality.
- [ ] Display the friend list on the user's profile.
- [ ] Create messaging capabilities for friends.
