### ISSUE TITLE
[USER STORY]: Book clubs

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#38]
Related to [Epic #6: Social Features and User Interactions](https://github.com/chl03rivs/bookwyrms-alliance/issues/10)

- *As a* registered user,
- *I want* to have the option to join a book club,
- *So that* I can have a smaller community to focus on.

## ACCEPTANCE CRITERIA:

- [ ] Users can join or create book clubs.
- [ ] Book clubs have their own dedicated discussion boards.
- [ ] Users can see which book clubs they are a part of from their profile.

## TASKS:

- [ ] Design and create the database model for book clubs and memberships.
- [ ]  Add "Join Club" and "Leave Club" buttons to book club pages.
- [ ]  Implement backend logic to handle book club membership requests.
- [ ]  Create a page that displays book club members and relevant discussions.
- [ ] Add Bookclub page to the website navigation
- [ ]  Test the book club joining and leaving functionality.
