### ISSUE TITLE
[EPIC #1]: User Account and Profile Management

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#4]
* **Description**: Managing user accounts, including registration, login, profile customization, and password recovery.
* **User stories**:
  - [ ]  [USER STORY: User registration](x)
  - [ ]  [USER STORY: User login](x)
  - [ ]  [USER STORY: User logout](x)
  - [ ]  [USER STORY: Profile customization](x)
  - [ ]  [USER STORY: Change profile information](x)
  - [ ]  [USER STORY: Password recovery](x)
  - [ ] [USER STORY: View user’s recent activity on profile](x)
