### ISSUE TITLE
Epic #2: Content Discovery and Navigation

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#6]
* Description: Allowing users to search for, view, and filter content (posts, books, authors, genres) for a personalized experience.

* User stories:
  - [ ] [USER STORY: Search for books, authors, genres](x)
  - [ ] [USER STORY: View posts and comments](x)
  - [ ] [USER STORY: Filter content by genre or tags](x)
  - [ ] [USER STORY: Filter posts by author/genre/topic](x)
