### ISSUE TITLE
[EPIC #3]: Post and Comment Management

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#8]
* **Description**: Enabling users to create and edit posts and comments related to books, authors, and other discussions.

* **User stories**:
  - [ ] [USER STORY: Creating posts](https://github.com/chl03rivs/bookwyrms-alliance/issues/21)
  - [ ] [USER STORY: Write a post about non-book topics](https://github.com/chl03rivs/bookwyrms-alliance/issues/22)
  - [ ] [USER STORY: Comments and posts updates](https://github.com/chl03rivs/bookwyrms-alliance/issues/24)
  - [ ]  [USER STORY: Delete a post or comment](https://github.com/chl03rivs/bookwyrms-alliance/issues/41)
  - [ ] [USER STORY: Submit comments on posts](https://github.com/chl03rivs/bookwyrms-alliance/issues/23)
