### ISSUE TITLE
[EPIC #5]: Admin Tools and Moderation

### ISSUE THREAD

**Issue by chl03rivs** [chl03rivs/bookwyrms-alliance#9]
* **Description**: Providing administrators with tools for moderating user activity, managing content, and maintaining a safe platform.

* **User stories**:
  - [ ] [USER STORY: Admin dashboard for managing requests](x)
  - [ ] [USER STORY: Suspend or ban users](x)
  - [ ] [USER STORY: Remove user’s post or comment](x)
  - [ ] [USER STORY: Flagged content moderation on mobile](x)
